apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  # default service is cluster-ip if not specified.
  type: NodePort
  selector:
    app: <pod-label-to-attach>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080